collectGarbage: true
logSeverity: Info
openVSX:
  release:
    eamodio:
    - gitlens
    rust-lang:
    - rust-analyzer
    stkb:
    - rewrap
vscodeMarketplace:
  release:
    eamodio:
    - gitlens
    github:
    - copilot
    - copilot-chat
    ms-vscode-remote:
    - remote-ssh
    rust-lang:
    - rust-analyzer
    stkb:
    - rewrap