jobs:
  nixCI:
    name: Nix CI
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
            keep-outputs = true
      - name: Restore and cache Nix store
        uses: deemp/cache-nix-too@v1
        with:
          key: nix-${{ matrix.os }}-update-${{ hashfiles('**/flake.nix', '**/flake.lock', 'haskell/**/*') }}
          linux-gc-enabled: true
          linux-max-store-size: 5000000000
          restore-keys: |
            nix-${{ matrix.os }}-update-${{ hashfiles('**/flake.nix', '**/flake.lock', 'haskell/**/*') }}
            nix-${{ matrix.os }}-update-
      - if: matrix.os == 'ubuntu-22.04'
        name: Config git for github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update codelldb.nix
        run: |
          export aarch64_darwin=`nix-prefetch-url https://github.com/vadimcn/codelldb/releases/download/v1.9.2/codelldb-aarch64-darwin.vsix`;
          export aarch64_linux=`nix-prefetch-url https://github.com/vadimcn/codelldb/releases/download/v1.9.2/codelldb-aarch64-linux.vsix`;
          export x86_64_darwin=`nix-prefetch-url https://github.com/vadimcn/codelldb/releases/download/v1.9.2/codelldb-x86_64-darwin.vsix`;
          export x86_64_linux=`nix-prefetch-url https://github.com/vadimcn/codelldb/releases/download/v1.9.2/codelldb-x86_64-linux.vsix`;
          python3 ./nix-files/update_codelldb.py > ./nix-files/codelldb.nix

      - env:
          CONFIG: .github/config.yaml
        name: Update extensions
        run: |+
          nix profile install nix-dev/#updateExtensions
          nix run nix-dev/#updateExtensions

      - name: Commit and push changes.
        run: |
          git add .
          git commit --allow-empty -m "action: update extensions"
          git push
    strategy:
      matrix:
        os:
          - ubuntu-22.04
name: Nix CI
"on":
  pull_request: {}
  push: {}
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
